on:
 schedule:
  - cron: '0 */6 * * *'
name: Scrape and publish
jobs:
 build:
  name: Build
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@master
   - uses: actions/setup-python@v4
     with:
      python-version: '3.10'
      cache: 'pip'
   - run: |
      pip install -r requirements.txt
      python main.py
   - uses: mikeal/publish-to-github-action@master
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
